capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>", views.detail, name="detail"),
    path("post/", views.make_post, name="post"),
    # Authentication
    path("authenticate_user/", views.authenticate_user, name="authenticate_user"),
    path("login/", views.user_login, name="login"),
    path("register/", views.user_registration, name="register"),
    path("logout/", views.user_logout, name="logout"),
]

posts/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField(max_length=512)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment_text


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ("author", "date")


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ("post", "author", "date")

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import CommentForm, Post, PostForm

# Authentication
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm


# index
def index(request):
    """The function to render the index page

    :return: render of the index page
    :rtype: HttpResponse"""
    latest_post_list = Post.objects.order_by("-date")[:8]
    context = {"latest_post_list": latest_post_list}
    return render(request, "index.html", context)


# detail
def detail(request, post_id):
    """Function to render the detail of a post, as well as a form to submit comments on the post

    :param post_id: the id of the post to be rendered
    :type post_id: int

    :return: Render of the detail page
    :rtype: HttpResponse"""
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return HttpResponseRedirect("#")
    else:
        form = CommentForm()
    context = {"post": post, "form": form}
    return render(request, "detail.html", context)


def make_post(request):
    """Function to render the page containing the form to submit a post

    :return: Render of the post page and associated form
    :rtype: HttpResponse"""
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.title = form.cleaned_data.get("title")
            # post.content = form.cleaned_data.get("content")
            post.save()
            return HttpResponseRedirect(reverse("posts:index"))
    else:
        form = PostForm()
    return render(request, "post.html", {"form": form})


# Authentication


# user_authentication
def authenticate_user(request):
    """Function to authenticate a user, and, if successful, to redirect to the index page

    :return: redirection to the appropriate page
    :rtype: HttpResponse"""
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse("posts:login"))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse("posts:index"))


# user_login
def user_login(request):
    """Function to render login page

    :return: Render of the login page
    :rtype: HttpResponse"""
    return render(request, "login.html")


# user_registration
def user_registration(request):
    """Function to render the registration page and the associated form

    :return: Render of the registration page
    :rtype: HttpResponse"""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse("posts:index"))
    else:
        form = UserCreationForm()

    return render(request, "register.html", {"form": form})


# user_logout
def user_logout(request):
    """Function to log out a user

    :return: redirection to index page
    :rtype: HttpResponse"""
    logout(request)
    return HttpResponseRedirect(reverse("posts:index"))

posts/templates/detail.html
{% extends "header.html" %}
{% block content %}
{% load crispy_forms_tags %}

{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}

<div class="container py-5">
  <div class="row mb-5">
    <div class="col-md-8 col-xl-6 text-center mx-auto">
      <h2 class="fw-bold">{{post.title}}</h2>
      <p class="text-secondary">By {{post.author}} at {{post.date}}</p>
    </div>
  </div>
  <div class="row mx-auto text-center" style="max-width: 900px">
    <div class="col">
      <p>{{post.content}}</p>
    </div>
  </div>
</div>
<div class="container">
    {% for comment in post.comment_set.all %}
      <div class="row">
        <div class="col" style="text-align: center">
          <div class="card-body d-flex flex-column align-items-center">
          <p>{{comment.author}} at {{comment.date}} says:</p>
          <p>{{comment.comment_text}}</p>
          </div>
        </div>
      </div>
    {% endfor %}
</div>
<div class="container">
  <div class="row">
    <div class="col" style="text-align: center">
      {% if user.is_authenticated %}
      <form
        class="container d-flex flex-column justify-content-center align-items-center"
        action=""
        method="POST"
      >
        {% csrf_token %} 
        {{ form|crispy }}

        <input
          class="btn btn-primary text-center border rounded border-primary"
          style="
            background: var(--bs-primary);
            color: #ffffff;
            font-size: 16px;
            font-weight: bold;
            margin: 8px;
          "
          role="button"
          type="submit"
          value="Post Comment"
        />
      </form>
      {% else %}
      <a
        class="btn btn-primary text-center border rounded border-primary"
        style="
          background: var(--bs-primary);
          color: #ffffff;
          font-size: 16px;
          font-weight: bold;
          margin: 4px;
        "
        href="/login"
        role="button"
      >
        Login to Post a Comment
      </a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

posts/templates/header.html
{% load static %}
<!DOCTYPE html>
<html
  lang="en"
  style="
    --bs-body-bg: #3d3d3d;
    --bs-primary: #75c550;
    --bs-primary-rgb: 117, 197, 80;
    --bs-secondary: #bbbbbb;
    --bs-secondary-rgb: 187, 187, 187;
    --bs-body-color: #e3e3e3;
    --bs-dark: #232323;
    --bs-dark-rgb: 35, 35, 35;
  "
>
  <head>
    <meta charset="utf-8" />
    <meta
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
      name="viewport"
    />
    <title>{% block title %}Tinhat{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://use.fontawesome.com/releases/v5.12.0/css/all.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <nav
      class="navbar navbar-dark navbar-expand-md bg-dark d-flex justify-content-center align-content-center py-3"
    >
      <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="/">
          <span
            class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"
          >
            <svg
              class="icon icon-tabler icon-tabler-alien"
              fill="none"
              height="1em"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              style="font-size: 28px"
              viewbox="0 0 24 24"
              width="1em"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M0 0h24v24H0z" fill="none" stroke="none"></path>
              <path d="M11 17a2.5 2.5 0 0 0 2 0"></path>
              <path
                d="M12 3c-4.664 0 -7.396 2.331 -7.862 5.595a11.816 11.816 0 0 0 2 8.592a10.777 10.777 0 0 0 3.199 3.064c1.666 1 3.664 1 5.33 0a10.777 10.777 0 0 0 3.199 -3.064a11.89 11.89 0 0 0 2 -8.592c-.466 -3.265 -3.198 -5.595 -7.862 -5.595z"
              ></path>
              <line x1="8" x2="10" y1="11" y2="13"></line>
              <line x1="16" x2="14" y1="11" y2="13"></line>
            </svg>
          </span>
          <span> Tinhat </span>
        </a>
        <div
          class="d-flex justify-content-end align-items-center"
        >
        {% if user.is_authenticated %}
          <span
          style="margin: 4px;">
          Welcome, {{user.username}}</span>
          <a class="btn btn-primary text-center border rounded border-primary"
          style="
            background: var(--bs-primary);
            color: #ffffff;
            font-size: 16px;
            font-weight: bold;
            margin: 4px;
          " 
          href="/logout" role="button">
            Logout
          </a>
        {% else %}
          <a class="btn btn-primary text-center border rounded border-primary"
          style="
            background: var(--bs-primary);
            color: #ffffff;
            font-size: 16px;
            font-weight: bold;
            margin: 4px;
          " 
          href="/login" role="button">
            Login
          </a>
        {% endif %}
      </div>
    </nav>

    <section class="py-5">{% block content %} {% endblock %}</section>

    <footer class="text-center py-4">
      <div class="container">
        <div class="row">
          <div class="col">
            <p class="text-secondary my-2" style="color: var(--bs-secondary)">
              Copyright © 2023 Tinhat
            </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

posts/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="container py-5">
  <div class="row mb-5">
    <div class="col-md-8 col-xl-6 text-center mx-auto">
      <h2 class="fw-bold">Latest Posts</h2>
      <p class="text-secondary">Find the latest juicy gossip right here!</p>
      <a
        class="btn btn-primary text-center border-primary"
        style="
          background: var(--bs-primary);
          color: #ffffff;
          font-size: 16px;
          font-weight: bold;
          margin: 4px;
        "
        href="/post"
        role="button"
        >New Post</a
      >
    </div>
  </div>
  <div class="row mx-auto" style="max-width: 900px">
    <div class="col text-center">
      {% if latest_post_list %}
      <ul class="list-unstyled" style="padding: 4px">
        {% for post in latest_post_list %}
        <li style="padding: 4px; font-size: 20px">
          <a
            href="{% url 'posts:detail' post.id %}"
            style="text-decoration: none; color: var(--bs-primary)"
          >
            {{ post.title }}
          </a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>It's empty! No posts here D:</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

posts/templates/login.html
{% extends "header.html" %}
{% block content %}

<div class="container">
  <div class="row mb-5">
    <div class="col-md-8 col-xl-6 text-center mx-auto">
      <h2>Log in</h2>
      <p>Welcome back! Please log in to continue.</p>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-xl-4">
      <div class="card bg-dark mb-5">
        <div class="card-body d-flex flex-column align-items-center">
          <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
            <svg
              class="bi bi-person"
              fill="currentColor"
              height="1em"
              viewbox="0 0 16 16"
              width="1em"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"
              ></path>
            </svg>
          </div>
          <form
            class="text-center"
            action="{% url 'posts:authenticate_user' %}"
            method="post"
          >
            {% csrf_token %}

            <div class="mb-3">
              <input
                class="form-control"
                name="username"
                placeholder="Username"
                type="text"
                id="username"
                required
              />
            </div>
            <div class="mb-3">
              <input
                class="form-control"
                name="password"
                placeholder="Password"
                type="password"
                id="password"
                required
              />
            </div>
            <div class="mb-3">
              <button
                class="btn btn-primary border-primary d-block w-100"
                style="background: var(--bs-primary)"
                type="submit"
                href="/login"
              >
                Login
              </button>
            </div>
            <a href="/register" style="color: var(--bs-secondary)">
              Don't have an account?
            </a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

posts/templates/post.html
{% extends "header.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row mb-5">
    <div class="col-md-8 col-xl-6 text-center mx-auto">
      <h2>New Post</h2>
      <p>Share what's on your mind</p>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-xl-4">
      {% if user.is_authenticated %}
        <form
          class="container d-flex flex-column justify-content-center align-items-center"
          action=""
          method="POST"
        >
          {% csrf_token %} 
          {{ form|crispy }}

          <input
            class="btn btn-primary text-center border rounded border-primary"
            style="
              background: var(--bs-primary);
              color: #ffffff;
              font-size: 16px;
              font-weight: bold;
              margin: 8px;
            "
            role="button"
            type="submit"
            value="Post"
          />
        </form>
      {%else%}
        <div class="text-center">
          <a class="btn btn-primary text-center border rounded border-primary"
          style="
            background: var(--bs-primary);
            color: #ffffff;
            font-size: 16px;
            font-weight: bold;
            margin: 4px;
          " 
          href="/login" role="button">
            Login
          </a>
        </div>
      {%endif%}
  </div>
</div>
{% endblock %}

posts/templates/register.html
{% extends "header.html" %} {% block content %} {% load crispy_forms_tags %}
<div class="container">
  <div class="row mb-5">
    <div class="col-md-8 col-xl-6 text-center mx-auto">
      <h2>Register</h2>
      <p>Join our many other users in oversharing</p>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 col-xl-4">
      <div class="card bg-dark mb-5">
        <div class="card-body d-flex flex-column align-items-center">
          <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4">
            <svg
              class="bi bi-person"
              fill="currentColor"
              height="1em"
              viewbox="0 0 16 16"
              width="1em"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"
              ></path>
            </svg>
          </div>
          <form class="text-center" method="post">
            {% csrf_token %} {{ form|crispy }}
            <div class="mb-3">
              <button
                class="btn btn-primary border-primary d-block w-100"
                style="background: var(--bs-primary)"
                type="submit"
              >
                Register
              </button>
            </div>
            <a href="/login" style="color: var(--bs-secondary)">
              Already have an account?
            </a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}